insert into course ( name, author) values ('Learn AWS', 'in28minutes');
insert into course ( name, author) values ('Learn Spring', 'in28minutes');
insert into course ( name, author) values ('Learn Spring Boot', 'in28minutes');
insert into course ( name, author) values ('Learn Spring MVC', 'in28minutes');
insert into course ( name, author) values ('Learn Spring Security', 'in28minutes');
insert into course ( name, author) values ('Learn Spring Cloud', 'in28minutes');
insert into course ( name, author) values ('Learn Spring Data JPA', 'in28minutes');
insert into course ( name, author) values ('Learn Azure', 'in28minutes');
insert into course ( name, author) values ('Learn Azure DevOps', 'in28minutes');
insert into course ( name, author) values ( 'Learn Azure Kubernetes', 'in28minutes');
insert into course ( name, author) values ( 'Learn GCP', 'in28minutes');
insert into course ( name, author) values ( 'Learn GCP Kubernetes', 'in28minutes');